### ISSUE TITLE
Add appropriate issue/PR labels

### ISSUE THREAD

**Issue by larryshamalama** [Kuan-Liu-Lab/causens#12]
Let's borrow from [PyMC](https://github.com/pymc-devs/pymc)

**Comment by Kuan-Liu** [comment]
Would this be helpful if we are building an R pacckage?

**Comment by larryshamalama** [comment]
It think that it would be helpful, but not necessary, especially in the beginning. Let's see?

**Comment by larryshamalama** [comment]
Done ✌️
