### ISSUE TITLE
Binary outcome for the first version of the sensitivity analysis

### ISSUE THREAD

**Issue by Kuan-Liu** [Kuan-Liu-Lab/causens#9]
Binary outcome has better statistical property, the senstivity function derived using binary outcome is bounded by -1 and 1:

$$ \text{sens} = E(Y^a \mid A=1, X) - E(Y^a \mid A=0, X) .$$ 

The bounds allow us to custermize prior for the bias parameters for the Bayesian approach and the specification of the sensitivity function of the frequentist Li's approach.

**Comment by larryshamalama** [comment]
Okay sounds good

**Comment by larryshamalama** [comment]
I looked into continuous outcomes, this issue addressed specifically binary outcome variables
